---
- hosts: webserver
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: hariapp
        image: "megatazm/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 10.0.2.5:8080:8080
